project:
  type: website
  output-dir: docs
  preview: 
    port: 5240
    browser: true
    
execute:
  freeze: auto

website:
  title: "Nomilo Fishpond Biogeochemical Analysis"
  navbar:
    left:
      - href: correlational-analysis.qmd
        text: Correlational Analysis
      - href: fieldwork-templates.qmd
        text: Fieldwork Templates
  back-to-top-navigation: true
    
format:
  html:
    theme: 
      - lumen
      - styles.scss
    toc: true
    fontsize: 15pt
    page-layout: full



