project:
  type: website
  output-dir: docs
  preview: 
    port: 5240
    browser: true
    
execute:
  freeze: auto

website:
  title: "Nomilo Fishpond Biogeochemical Analysis"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: data-processing.qmd
        text: Data Processing
      - href: data-collection.qmd
        text: Data Collection App
      - href: eda.qmd
        text: EDA App
      - href: correlational-analysis.qmd
        text: Correlational Analysis
  back-to-top-navigation: true
    
format:
  html:
    theme: 
      - simplex
      # - styles.scss
    toc: true
    fontsize: 12pt
    page-layout: full
    link-external-newwindow: true
    margin-header: |
      <br>
      ![](/www/logos/uhm-logo.png) 
      <br><br>
      ![](/www/logos/pac-risa-logo.png) 
      <br><br>



