project:
  type: website
  output-dir: docs
  preview: 
    port: 5240
    browser: true
    
execute:
  freeze: auto

website:
  title: "Nomilo Fishpond Case Study"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: data-processing.qmd
        text: Data Processing
      - href: data-explorer-dashboard.qmd
        text: Data Explorer Dashboard
  back-to-top-navigation: true
    
format:
  html:
    theme: 
      - simplex
    toc: true
    fontsize: 12pt
    page-layout: full
    link-external-newwindow: true
    margin-header: |
      <br>
      ![](/www/logos/uhm-logo.png) 
      <br><br>
      ![](/www/logos/pac-risa-logo.png) 
      <br><br>
      ![](/www/logos/ksf-logo.png) 
      <br><br>



