---
title: "Correlational Analysis"
author: 
  - name: "Lysbeth Koster"
  - name: "Alemarie Ceria"
date: "02/28/2024"
execute: 
  warning: false
  message: false
code-annotations: hover
code-overflow: wrap
---

::: {.panel-tabset}

## Clams

### All Relationships

```{r}
#| eval: false
#| echo: false
# Select only numeric columns for correlation analysis
clams_growth_biogeochem_vars_numeric_data <- clams_growth_biogeochem_vars_merged %>%
  select_if(is.numeric) %>% 
  select(-days_btwn_clams_sort)

# Compute the correlation matrix
clams_growth_biogeochem_vars_corr_matrix <- cor(clams_growth_biogeochem_vars_numeric_data)
```

```{r}
#| eval: false
#| echo: false
kable(clams_growth_biogeochem_vars_corr_matrix, caption = "KSF Clams Growth and Environmental Variables Correlation Matrix") %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover"))
```

</br>

```{r}
#| eval: false
#| echo: false
#| fig-align: center
#| fig-width: 20
#| fig-height: 20
corrplot(clams_growth_biogeochem_vars_corr_matrix, method = "circle",
         tl.cex = 2, # Text label size, change as needed
         tl.col = "black", # Text label color
         tl.srt = 90, # Text label rotation in degrees
         tl.offset = 0.5, 
         cl.pos = "b"
        )
```

### Specific Relationship

```{r}
#| eval: false
#| echo: false
#| code-fold: true
#| code-summary: Correlation Between Interpolated Weight and Interpolated Dissolved Oxygen
results <- corr.test(x = clams_growth_biogeochem_vars_interp$clams_count, 
                     y = clams_growth_biogeochem_vars_interp$dissolved_oxygen,
                     method = "pearson", ci = TRUE)

print(results, short=FALSE)
```

```{r}
#| eval: false
#| echo: false
#| code-fold: true
#| code-summary: Adjusted P-Value
adjusted_p_values <- results$p.adj
print(adjusted_p_values)
```

## Oysters 

### All Relationships

### Specific Relationship

:::
